Install-Module -Name xCertificate -Force
Install-Module -Name cChoco -Force
Install-Module -Name Carbon -Force
Install-Module -Name ComputerManagementDSC -Force
Install-Module -Name cDTC -Force
Install-Module -Name NetworkingDsc -Force
Install-Module -name xWebAdministration -Force
Install-Module -name cNtfsAccessControl -Force
Install-Module -name xSmbShare -Force
Install-Module -Name Mario_cVSS -Force
Install-Module -Name xDSCDomainJoin -Force
Install-Module -Name SecurityPolicyDsc -Force